[build]
  publish = "build/web"
  command = "[ -d _flutter ] || git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter && _flutter/bin/flutter build web --release --dart-define=API_BASE_URL=https://attendance-rfid.onrender.com/api/v1 --dart-define=WS_URL=https://attendance-rfid.onrender.com"
