#!/usr/bin/env python3
"""
generate_env.py — create a .env with fresh secrets for ONE customer.

Run this once per customer installation:
    python generate_env.py

Every customer gets unique secrets — never reuse a .env between
customers (especially CAMERA_API_KEY, which goes into their RFID
readers).
"""
import secrets
from pathlib import Path

ENV_FILE = Path(__file__).parent / ".env"


def token() -> str:
    return secrets.token_urlsafe(32)


def main():
    if ENV_FILE.exists():
        ans = input(".env already exists — overwrite? [y/N] ").strip().lower()
        if ans != "y":
            print("Aborted.")
            return

    customer    = input("Customer name (for reference)   : ").strip() or "customer"
    admin_email = input("Admin email    [admin@attendease.com]: ").strip() or "admin@attendease.com"
    admin_pass  = input("Admin password [auto-generate]        : ").strip() or ("Aa1!" + token()[:12])
    port        = input("Backend port   [5000]                 : ").strip() or "5000"

    camera_key = token()

    content = f"""# AttendEase deployment — {customer}
# Generated by generate_env.py — DO NOT COMMIT, DO NOT REUSE for other customers

BACKEND_PORT={port}

POSTGRES_PASSWORD={token()}
SECRET_KEY={token()}
JWT_SECRET_KEY={token()}
JWT_REFRESH_SECRET={token()}

# This key goes into the RFID reader's setup page ("API key" field)
CAMERA_API_KEY={camera_key}

ADMIN_EMAIL={admin_email}
ADMIN_PASSWORD={admin_pass}

# Comma-separated origins allowed to call the API (add the customer's
# dashboard URL if the Flutter web app is hosted somewhere)
CORS_ORIGINS=http://localhost:3000,http://localhost:8080
"""
    ENV_FILE.write_text(content, encoding="utf-8")

    print("\n.env written.")
    print("─" * 52)
    print(f"  Customer      : {customer}")
    print(f"  Admin login   : {admin_email} / {admin_pass}")
    print(f"  Reader API key: {camera_key}")
    print("─" * 52)
    print("Enter the Reader API key on each RFID reader's setup page.")
    print("Next: docker compose up -d --build")


if __name__ == "__main__":
    main()
